apiVersion: apps/v1
kind: StatefulSet
metadata:
  name:  nginx-app
  labels:
    name:  nginx-app
spec:
  selector:
    matchLabels:
      app: nginx-app
  serviceName: nginx-app
  replicas: 2
  template:
    metadata:
      labels:
        name:  nginx-app
    spec:
      containers:
        - image: nginx:1.19.0
          name: nginx-app
          env:
            - name: NGINX_USER
              value: admin
            - name: NGINX_PASS
              value: password
          volumeMounts:
            - name:  nginx_volume
              mountPath: /data/app
      volumes:
        - name: nginx_volume
          persistentVolumeClaim:
            claimName: "nginx-pvc"
    volumeClaimTemplates:
      - apiVersion: v1
        kind: PersistentVolumeClaim
      - metadata:
          name: "nginx-pvc"
        spec:
          accessModes: ["ReadWriteOnce"]
          StorageClassName: test-storage
          resource:
            requests:
              storage: 1Gi
         
