apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name:  nginx-deployment
  labels:
    name:  nginx-app
spec:
  selector:
    matchLabels:
      app: nginx-app
  serviceName: nginx-app
  replicas: 2
  template:
    metadata:
      labels:
        app:  nginx-app
    spec:
      containers:
        - name: nginx-app
          image: bnishanthi/nginx-deployment:1.0
          env:
            - name: NGINX_USER
              value: "admin"
            - name: NGINX_PASS
              value: "password"
          ports:
          - containerPort: 3001
            name: webserver
          volumeMounts:
            - name:  csivolume
              mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: csivolume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "csi-hostpath-sc"
      resources:
        requests:
          storage: 1Gi
         
